### ISSUE TITLE
Slackのロゴでモザイクアートを作成しようとしたところ、IndexErrorが解決できない

### ISSUE THREAD

**Issue by ftnext** [ftnext/mosaic-art-python#12]
1/16のデモ中に発生。

対象画像：
http://iosicongallery.com/img/512/slack-2014-10-07.png

モザイクアート作成用のディレクトリに保存し、ソースコードで対象ファイル名を変更。
モザイクアート作成を実行したところ、以下のエラーが出た。

```Traceback (most recent call last):
  File "mosaic_art.py", line 114, in <module>
    main()
  File "mosaic_art.py", line 28, in main
    left+DOT_AREA_ONE_SIDE, top+DOT_AREA_ONE_SIDE)
  File "[パスの一部を省略]/20171202mosaic-art-python/mosaic_art/calc.py", line 30, in average_color_in_range
    green = round(mean_color[1])
IndexError: list index out of range
```

画像のサイズが512×512と10の倍数でないことが原因かと考え、
うまくいっている画像と同じ400×400サイズにしたが、
同じエラーが出て解決できなかった。

画像の問題の可能性があるので、ログを仕込んで原因を調査する想定。

**Comment by ftnext** [comment]
原因調査したところ、Imageオブジェクトのmodeが原因であることが判明。

https://pillow.readthedocs.io/en/5.0.0/handbook/concepts.html#concept-modes

対象のslackのアイコン画像をopenしたImageオブジェクトのmodeはP
>P (8-bit pixels, mapped to any other mode using a color palette)

これまでモザイクアートが正常に動いていた画像のImageオブジェクトのmodeはRGBA
>RGBA (4x8-bit pixels, true color with transparency mask)

modeがPの画像についてgetpixelすると返ってくる値は一つだけ（RGBAのタプルでない）
ImageStat.Stat.meanやmedianも一つの値しか返ってこない。（要素数1のリスト）
そのためgreenにアクセスしようとしたときにインデックスがout of rangeで落ちていた。

modeをPからRGBAにconvertすることでモザイクアートが作成できることを確認。
画像を開いた後にmodeをチェックして必要であればconvertする処理を追加する。

**Comment by ftnext** [comment]
本件対応中。
`Image.open`した後、画像の色を計算する処理をするが、
modeがPだとリスト外のインデックスを参照してしまい落ちる可能性がある。
そこでmodeをRGBAに変換し、リスト外のインデックスを参照しないようにする。

`Image.open`でソースコードを検索し、対応が必要なファイルと箇所を特定した。
- mosaic_art.py（＊）
- mosaic_art_median.py（＊）
- mosaic_art_mode.py（＊）
- calculate_material_color.py
- dot_picture.py

（＊）のファイルでは2箇所で`Image.open`している。
area_imとしてopenしている方は画像の色を変換しないので、修正不要と考えている。

以下のファイルは縮小処理であり、画像の色を計算するわけではないので対応不要の認識。
- thumbnail_image.py

**Comment by ftnext** [comment]
997be01 まで各ファイルに関数を用意し、その関数を使う修正を進めてきた。
calculate_material_color.pyについても同様に関数を追加し、それを適用したところ、
素材画像がRGBですべてRGBAに変換されてしまうことが判明した。
RGBでもRGBAでもR,G,Bの3色が取得できればいいので、変換は不要の認識。
そこで今回導入する関数を、modeがRGBでもRGBAでもないときにRGBAにconvertするように修正する。

すべてのファイルの関数を書き換えるのは面倒なので、
calcのようにモジュール化し、必要なファイルでimportするように修正する。
